bump version to 2.0.0
near/rainbow-bridge-cli pull request #360
Opened 2020-09-30 17:20 UTC by ailisp

2020-09-30 17:25 UTC, nearmax requested changes
This change is incorrect. We need to first publish 1.1.3 that reverts the token factory, and we need to do it for all rainbow-bridge repos. Then we need to publish 2.0.0 that introduces it.

2020-09-30 23:31 UTC, ailisp commented
transfer to near fully works. but from near has "proof is not valid error":
https://rinkeby.etherscan.io/tx/0x4c74014bc496232994612fcb49729749cfb283ab51f72cf3abf9967e60c9cfe6

still investigating

2020-10-02 20:48 UTC, nearmax approved these changes

2020-10-02 20:52 UTC, nearmax approved these changes
Verified that it works locally and on Rinkeby.

2020-10-03 00:06 UTC, merged